### PR TITLE
Switch to NEXT.js

### PR DESCRIPTION
**Pull request by jajaperson**
# Switch to [`NEXT.js`](https://github.com/zeit/next.js)

_Okay, this is embaressing_

## Participants

- **@jajaperson — James Jensen** (me)
- @oscartbeaumont — Oscar Beaumont

### Why `StencilJS` was a bad decision (on my behalf)

`StencilJS` is amazing, and so is the whole WebComponents movement, but the
ecosystem is still very young and unpolished. When I started this project, I
thought that using `StencilJS` would be a good decision (i.e. that it would
actually boost our productivity), as I really liked its ideology, project
structure, and features. However, it didn't take very long for the ugly part of
working with young frameworks/ecosystems to rear its large, ugly head.

### `NEXT.js`: A better choice

You might already know `NEXT.js`. It's a
framework that basically offers <abbr title="Server Side Rendering">SSR</abbr>
for React apps. This makes it the ideal front-end framework for static websites.
It's a perfect fit for this project, which is why I would like to switch to it.
It:

- Has a familiar, well thought-out project structure.
- Works really well for static websites.
- Allows for the `Component/Page` pattern.
- Is made by the amazing team at @Zeit.

### Proving `NEXT.js` is a better choice

To prove that `NEXT.js` is a better choice, and that this isn't the same
pipe-dream that using `StencilJS` was, I have already got the project to the
same point as the old one was, as well as solve some of the issues we were
having with the old one.

## I'm sorry

I get this is a bit annoying, at the beginning of this project I had to put a
lot of work into pursuading everyone that `StencilJS` was ideal. But that was my
mistake, and for that I'm sorry. What's important is that we now move past it
and get this website up and running.

## The _NEW_ stack!

- [`NEXT.js`](https://github.com/zeit/next.js)/React with SSR for UI
- [`styled-components`](https://github.com/styled-components/styled-components)
  for styling
- [`ESLint`](https://github.com/eslint/eslint) for static analysis
- [`prettier`](https://github.com/prettier/prettier) for code style
- [`MDX`](https://github.com/mdx-js/mdx) for content
- [`AVA`](https://github.com/avajs/ava) for testing (probably)
- [`▲ now.sh`](https://now.sh) for deployments (maybe —
  [see below](#Deployment)).

## Deployment???

Okay, so it looks like we might be moving from GitHub pages, to `▲ now.sh`, to
Netlify, and now to `▲ now.sh` again. `▲ now.sh` has some great features when it
comes to `NextJS` apps, so I think it might be the ideal setup here.
@OscarTBeaumont thoughts???

## Other stuff

- We might also want to look into using [`mdx`](https://github.com/mdx-js/mdx)
  for page content.

### CODE REVIEW

**Comment by oscartbeaumont** [comment]
Do you use yarn or npm (hopefull yarn but I think you don't)?

**Comment by oscartbeaumont** [comment]
Also can anything happen about removing the `.vscode` folder because that is specific to your setup and imo shouldn't go in the main repo.

**Comment by jajaperson** [comment]
I use NPM, and I probably won't be changing anytime soon. Yarn looks great, but I'd rather stick with the industry standard. Someone who has used Yarn will almost definitely also be familiar with NPM, but no so much the other way 'round.

In terms of the `.vscode` folder (yes, I know, I gone to the dark side), all it has is the one `formatOnSave` option, which I feel should be kept in order to automatically have that feature on anyone using viscose (e.g. if I clone the repo on another computer). If a similar feature exists on Atom (or any other text editor you use), I recommend you do the same.

**Comment by jajaperson** [comment]
@oscartbeaumont any progress?

**Comment by oscartbeaumont** [comment]
Yer I have done a bit I am still cleaning up a few things before the merge.

**Comment by jajaperson** [comment]
Okay, I've set up `MDX` now. Here's how it will work:

- All content `.mdx` files will live in **`/sections/`**.
- **`/sections/`** will be divided into (surprise) sections, such as **`/sections/homepage`** and **`/sections/contact`**.
- `.mdx` files should have an export `{ meta }` containing metadata (comparable to front-matter).

**Comment by oscartbeaumont** [comment]
We have come across a problem. Content management. How do you intend for someone at PKFI to be able to update the content on the website? Cause my existing solution is not really designed to work with Now.sh even though it could possibly be hacked together to do so.

**Comment by oscartbeaumont** [comment]
Also, I have no clue if the solution I was going to use would be easy to work with the Mdx syntax (again haven't checked and it could be perfectly fine).

**Comment by jajaperson** [comment]
It could be a *bit* of a stretch, but do you think the folks at PKFI would be able to understand `.mdx` as it is? 🤷‍♂️ I mean, for most of the stuff here, it will be comparable to plaintext.

**Comment by jajaperson** [comment]
Maybe this will help??? <https://github.com/now-examples/ghost>

**Comment by jajaperson** [comment]
Although that seems primarily for blogging.

**Pull request merged**
